spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/giftfunding?serverTimeZone=UTC&characterEncoding=UTF-8
    username: giftfunding
    password: soni