name: Java CI With Gradle

on:
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: grant execute permission for gradlew
        run: chmod +777 gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test